on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  require_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title || '';
            const body  = pr.body  || '';

            // 권장: "Closes #123" 패턴
            const linkRe  = /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#\d+/i;
            // 최소: "#123" 참조
            const bareRe  = /(^|\s)#\d+(\s|$)/;

            if (linkRe.test(title) || linkRe.test(body) || bareRe.test(title) || bareRe.test(body)) {
              core.info('Linked issue found ✅');
            } else {
              core.setFailed('PR must reference an issue: include "Closes #123" (recommended) or at least "#123" in title or body.');
            }
