on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const text = `${pr.title || ''}\n${pr.body || ''}`;
            const m = text.match(/#(\d+)/);
            if (!m) { core.info('No issue reference found. Skipping.'); return; }
            const issue_number = Number(m[1]);

            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner, repo: context.repo.repo, issue_number
            });

            const labels = (issue.labels || [])
              .map(l => typeof l === 'string' ? l : l.name)
              .filter(Boolean);

            if (!labels.length) { core.info(`Issue #${issue_number} has no labels.`); return; }

            await github.rest.issues.addLabels({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: pr.number, labels
            });
            core.info(`Synced labels [${labels.join(', ')}] from issue #${issue_number} to PR #${pr.number}`);
